{{range $i, $e := until (atoi (printf "%d" (int64 .Values.replicaCount))) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{$i}}
  labels:
    app: {{ template "clickhouse-on-kube.name" $ }}
    chart: {{ template "clickhouse-on-kube.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: {{ $.Values.service.type }}
  ports:
  - name: rpc
    port: {{ $.Values.service.rpc_port }}
    targetPort: {{ $.Values.service.rpc_port }}
    protocol: TCP
  - name: rest
    port: {{ $.Values.service.rest_port }}
    targetPort: {{ $.Values.service.rest_port }}
    protocol: TCP
  - name: interserver
    port: 9009
    targetPort: 9009
    protocol: TCP
  selector:
    app: {{ $.Release.Name }}
    shard_name: {{ $.Release.Name }}-{{$i}}
    release: {{ $.Release.Name }}
---
{{end}}
# --- elb ---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-client-svc"
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "clickhouse-on-kube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: rpc
    port: {{ $.Values.service.rpc_port }}
    targetPort: {{ $.Values.service.rpc_port }}
    protocol: TCP
  - name: rest
    port: {{ $.Values.service.rest_port }}
    targetPort: {{ $.Values.service.rest_port }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
    release: {{ $.Release.Name }}
  sessionAffinity: None
  type: ClusterIP
